// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RetailAndStockManagement.Data.EF;

#nullable disable

namespace RetailAndStockManagement.Data.Migrations
{
    [DbContext(typeof(RetailAndStockManagementContext))]
    [Migration("20260519202846_InitialWithSizes")]
    partial class InitialWithSizes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CountryModel", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("RegionModel", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegionId"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RegionId");

                    b.HasIndex("CountryId");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("RetailAndStockManagement.Data.EF.ProductModel", b =>
                {
                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImageBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductProperties")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Barcode");

                    b.ToTable("Product", "dbo");
                });

            modelBuilder.Entity("RetailAndStockManagement.Data.EF.ProductStoreModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("OptionCount")
                        .HasColumnType("int");

                    b.Property<int>("SizeL")
                        .HasColumnType("int");

                    b.Property<int>("SizeM")
                        .HasColumnType("int");

                    b.Property<int>("SizeS")
                        .HasColumnType("int");

                    b.Property<int>("SizeXL")
                        .HasColumnType("int");

                    b.Property<int>("SizeXS")
                        .HasColumnType("int");

                    b.Property<int>("SizeXXL")
                        .HasColumnType("int");

                    b.Property<int>("SizeXXXL")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Barcode");

                    b.HasIndex("StoreId");

                    b.ToTable("ProductStore", "dbo");
                });

            modelBuilder.Entity("RetailAndStockManagement.Data.EF.StoreModel", b =>
                {
                    b.Property<int>("StoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoreId"));

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<string>("StoreLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoreLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("StoreLocation");

                    b.HasKey("StoreId");

                    b.HasIndex("RegionId");

                    b.ToTable("Store", "dbo");
                });

            modelBuilder.Entity("RetailAndStockManagement.Data.EF.TransferOrderModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("QtyL")
                        .HasColumnType("int");

                    b.Property<int>("QtyM")
                        .HasColumnType("int");

                    b.Property<int>("QtyS")
                        .HasColumnType("int");

                    b.Property<int>("QtyXL")
                        .HasColumnType("int");

                    b.Property<int>("QtyXS")
                        .HasColumnType("int");

                    b.Property<int>("QtyXXL")
                        .HasColumnType("int");

                    b.Property<int>("QtyXXXL")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TargetStoreId")
                        .HasColumnType("int");

                    b.Property<int>("TransferRequestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("TargetStoreId");

                    b.HasIndex("TransferRequestId");

                    b.ToTable("TransferOrder", "dbo");
                });

            modelBuilder.Entity("RetailAndStockManagement.Data.EF.TransferRequestModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RemL")
                        .HasColumnType("int");

                    b.Property<int>("RemM")
                        .HasColumnType("int");

                    b.Property<int>("RemS")
                        .HasColumnType("int");

                    b.Property<int>("RemXL")
                        .HasColumnType("int");

                    b.Property<int>("RemXS")
                        .HasColumnType("int");

                    b.Property<int>("RemXXL")
                        .HasColumnType("int");

                    b.Property<int>("RemXXXL")
                        .HasColumnType("int");

                    b.Property<int>("RemainingQuantity")
                        .HasColumnType("int");

                    b.Property<int>("ReqL")
                        .HasColumnType("int");

                    b.Property<int>("ReqM")
                        .HasColumnType("int");

                    b.Property<int>("ReqS")
                        .HasColumnType("int");

                    b.Property<int>("ReqXL")
                        .HasColumnType("int");

                    b.Property<int>("ReqXS")
                        .HasColumnType("int");

                    b.Property<int>("ReqXXL")
                        .HasColumnType("int");

                    b.Property<int>("ReqXXXL")
                        .HasColumnType("int");

                    b.Property<int>("SourceStoreId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Barcode");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("SourceStoreId");

                    b.ToTable("TransferRequest", "dbo");
                });

            modelBuilder.Entity("RetailAndStockManagement.Data.EF.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("StoreId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("User", "dbo");
                });

            modelBuilder.Entity("RegionModel", b =>
                {
                    b.HasOne("CountryModel", "Country")
                        .WithMany("Regions")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("RetailAndStockManagement.Data.EF.ProductStoreModel", b =>
                {
                    b.HasOne("RetailAndStockManagement.Data.EF.ProductModel", "Product")
                        .WithMany()
                        .HasForeignKey("Barcode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RetailAndStockManagement.Data.EF.StoreModel", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("RetailAndStockManagement.Data.EF.StoreModel", b =>
                {
                    b.HasOne("RegionModel", "Region")
                        .WithMany("Stores")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("RetailAndStockManagement.Data.EF.TransferOrderModel", b =>
                {
                    b.HasOne("RetailAndStockManagement.Data.EF.UserModel", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RetailAndStockManagement.Data.EF.StoreModel", "TargetStore")
                        .WithMany()
                        .HasForeignKey("TargetStoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RetailAndStockManagement.Data.EF.TransferRequestModel", "TransferRequest")
                        .WithMany("TransferOrders")
                        .HasForeignKey("TransferRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("TargetStore");

                    b.Navigation("TransferRequest");
                });

            modelBuilder.Entity("RetailAndStockManagement.Data.EF.TransferRequestModel", b =>
                {
                    b.HasOne("RetailAndStockManagement.Data.EF.ProductModel", "Product")
                        .WithMany()
                        .HasForeignKey("Barcode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RetailAndStockManagement.Data.EF.UserModel", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RetailAndStockManagement.Data.EF.StoreModel", "SourceStore")
                        .WithMany()
                        .HasForeignKey("SourceStoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Product");

                    b.Navigation("SourceStore");
                });

            modelBuilder.Entity("RetailAndStockManagement.Data.EF.UserModel", b =>
                {
                    b.HasOne("RetailAndStockManagement.Data.EF.StoreModel", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Store");
                });

            modelBuilder.Entity("CountryModel", b =>
                {
                    b.Navigation("Regions");
                });

            modelBuilder.Entity("RegionModel", b =>
                {
                    b.Navigation("Stores");
                });

            modelBuilder.Entity("RetailAndStockManagement.Data.EF.TransferRequestModel", b =>
                {
                    b.Navigation("TransferOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
